-- Access control module tables for Netty IoT gateway
CREATE TABLE IF NOT EXISTS iot_acc_device (
    id            varchar(32)  NOT NULL,
    create_by     varchar(64)  DEFAULT NULL,
    create_time   datetime     DEFAULT NULL,
    update_by     varchar(64)  DEFAULT NULL,
    update_time   datetime     DEFAULT NULL,
    sn            varchar(64)  NOT NULL,
    device_type   varchar(32)  DEFAULT NULL,
    device_name   varchar(128) DEFAULT NULL,
    firmware_version varchar(128) DEFAULT NULL,
    push_version  varchar(64)  DEFAULT NULL,
    lock_count    int          DEFAULT NULL,
    reader_count  int          DEFAULT NULL,
    machine_type  int          DEFAULT NULL,
    ip_address    varchar(64)  DEFAULT NULL,
    gateway_ip    varchar(64)  DEFAULT NULL,
    net_mask      varchar(64)  DEFAULT NULL,
    init_payload  text,
    registry_payload text,
    last_known_ip varchar(64)  DEFAULT NULL,
    last_init_time datetime    DEFAULT NULL,
    last_registry_time datetime DEFAULT NULL,
    last_heartbeat_time datetime DEFAULT NULL,
    status        varchar(32)  DEFAULT NULL,
    authorized    bit(1)       DEFAULT NULL,
    registry_code varchar(128) DEFAULT NULL,
    remark        varchar(255) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_acc_device_sn (sn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Access control devices reported by Netty gateway';

CREATE TABLE IF NOT EXISTS iot_acc_device_rtlog (
    id            varchar(32)  NOT NULL,
    create_by     varchar(64)  DEFAULT NULL,
    create_time   datetime     DEFAULT NULL,
    update_by     varchar(64)  DEFAULT NULL,
    update_time   datetime     DEFAULT NULL,
    sn            varchar(64)  NOT NULL,
    log_time      datetime     DEFAULT NULL,
    pin           varchar(64)  DEFAULT NULL,
    card_no       varchar(64)  DEFAULT NULL,
    event_addr    int          DEFAULT NULL,
    event_code    int          DEFAULT NULL,
    inout_status  int          DEFAULT NULL,
    verify_type   int          DEFAULT NULL,
    record_index  int          DEFAULT NULL,
    site_code     int          DEFAULT NULL,
    link_id       int          DEFAULT NULL,
    mask_flag     int          DEFAULT NULL,
    temperature   int          DEFAULT NULL,
    conv_temperature int       DEFAULT NULL,
    raw_payload   text,
    client_ip     varchar(64)  DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_acc_rtlog_sn_time (sn, log_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Real-time logs uploaded by access control devices';

CREATE TABLE IF NOT EXISTS iot_acc_device_state (
    id            varchar(32)  NOT NULL,
    create_by     varchar(64)  DEFAULT NULL,
    create_time   datetime     DEFAULT NULL,
    update_by     varchar(64)  DEFAULT NULL,
    update_time   datetime     DEFAULT NULL,
    sn            varchar(64)  NOT NULL,
    log_time      datetime     DEFAULT NULL,
    sensor        varchar(32)  DEFAULT NULL,
    relay         varchar(32)  DEFAULT NULL,
    alarm         varchar(64)  DEFAULT NULL,
    door          varchar(32)  DEFAULT NULL,
    raw_payload   text,
    client_ip     varchar(64)  DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_acc_state_sn_time (sn, log_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Door status snapshots reported by devices';

CREATE TABLE IF NOT EXISTS iot_acc_device_photo (
    id            varchar(32)  NOT NULL,
    create_by     varchar(64)  DEFAULT NULL,
    create_time   datetime     DEFAULT NULL,
    update_by     varchar(64)  DEFAULT NULL,
    update_time   datetime     DEFAULT NULL,
    sn            varchar(64)  NOT NULL,
    pin           varchar(128) DEFAULT NULL,
    photo_name    varchar(255) DEFAULT NULL,
    file_size     int          DEFAULT NULL,
    photo_base64  longtext,
    uploaded_time datetime     DEFAULT NULL,
    raw_payload   longtext,
    client_ip     varchar(64)  DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_acc_photo_sn_time (sn, uploaded_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Attendance photos uploaded by devices';

CREATE TABLE IF NOT EXISTS iot_acc_device_command_report (
    id            varchar(32)  NOT NULL,
    create_by     varchar(64)  DEFAULT NULL,
    create_time   datetime     DEFAULT NULL,
    update_by     varchar(64)  DEFAULT NULL,
    update_time   datetime     DEFAULT NULL,
    sn            varchar(64)  NOT NULL,
    command_id    varchar(128) DEFAULT NULL,
    command_content text,
    result_code   varchar(32)  DEFAULT NULL,
    result_message varchar(255) DEFAULT NULL,
    report_time   datetime     DEFAULT NULL,
    raw_payload   text,
    client_ip     varchar(64)  DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_acc_command_report_sn_time (sn, report_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Command execution feedback reported by devices';
